### ISSUE TITLE
week 3 Task List

### ISSUE THREAD

**Issue by evstarelan** [evstarelan/test-rep#4]
- [ ] Реализовать базу данных в MSSQL

- [ ] Заполнить повторяющимися конструкциями основную таблицу (>=1000 строк)

- [ ] Создать класс, описывающий задачу (несколько свойств взять из ТЗ)

- [ ] Считать структурированно дерево

**Comment by evstarelan** [comment]
- Разные версии БД (пустая, с красивым-коротким тестом, заполненная гигантским муссором) в папке BDscripts.

- Есть подходящая версия БД

- Было создано приложение TestTree, которое взаимодействует с БД через EF, читает информацию о задачах, выводит в виде дерева с помощью TreeView.
